### ISSUE TITLE
Move the persistence interfaces to a separate package

### ISSUE THREAD

**Issue by jageall** [IdentityServer/Thinktecture.IdentityServer3.Admin#9]
If the persistence interfaces are moved to a separate package, it will make it a lot easier for people like me to build persistence layers and other tooling around the identity server.

I believe that the only classes/interfaces that would need to be moved are IPersistence<TEntity>, PagingInformation and PageResult

**Comment by ManuelRauber** [comment]
Good point, especially after we moved the client into the admin project. I'll take a look at it.

**Comment by ManuelRauber** [comment]
Take a look at https://github.com/IdentityServer/Thinktecture.IdentityServer3.Admin.Persistence

We don't have a nuget yet :)
